"""Wiki media registry.

METHOD_MEDIA maps a method-table row name to the OSRS Wiki page whose image
represents it (NPC model, location shot, item icon). PROSE_ENTITIES is the
curated set of names that get an inline thumbnail when they appear in prose.

`python3 fetch_media.py` downloads everything here into assets/media/ and
writes assets/media/manifest.json, which build.py reads. Nothing here hits the
network at build time.
"""

# method row name -> wiki page title
METHOD_MEDIA = {
    # combat
    "Slayer tasks": "Slayer",
    "Nightmare Zone": "Nightmare Zone",
    "Nightmare Zone (all styles)": "Nightmare Zone",
    "Sulphur Nagua": "Sulphur Nagua",
    "Ammonite / sand crabs": "Ammonite Crab",
    "Bossing": "Zulrah",
    "Barbarian Fishing": "Leaping sturgeon",
    "Tempoross / Wintertodt": "Tempoross",
    "Cannon on Slayer tasks": "Dwarf multicannon",
    "Chinning – maniacal monkeys": "Maniacal monkey",
    "Chinning – Wilderness caves": "Black chinchompa",
    "Blowpipe on crabs / Nagua": "Toxic blowpipe",
    "Vorkath / bossing": "Vorkath",
    "Bursting/barraging Slayer tasks": "Ice Barrage",
    "Splashing": "Splashing",
    "High Alchemy": "High Level Alchemy",
    "Stun-alching": "Stun",
    "Powered staff on Slayer": "Trident of the seas",
    "Superheat / Enchant bolts": "Superheat Item",
    "Guardians of the Rift": "Guardians of the Rift",
    # prayer
    "Gilded altar – dragon bones": "Gilded altar",
    "Gilded altar – superior dragon bones": "Superior dragon bones",
    "Wilderness Chaos altar": "Chaos Temple (Wilderness)",
    "Ensouled heads": "Ensouled dragon head",
    "Ectofuntus": "Ectofuntus",
    # slayer masters
    "Nieve / Steve": "Nieve",
    "Konar quo Maten": "Konar quo Maten",
    "Duradel": "Duradel",
    "Krystilia (Wilderness)": "Krystilia",
    "Turael/Spria skipping": "Turael",
    # fishing / hunter
    "Drift Net Fishing": "Drift net fishing",
    "Minnows": "Minnow",
    "Tempoross": "Tempoross",
    "Karambwans": "Raw karambwan",
    "Anglerfish": "Raw anglerfish",
    "Hunter Rumours (Hunters' Guild)": "Hunter Guild",
    "Black chinchompas": "Black chinchompa",
    "Red chinchompas": "Red chinchompa",
    "Herbiboar": "Herbiboar",
    "Birdhouse runs": "Oak bird house",
    # agility
    "Rooftop courses": "Ardougne Rooftop Course",
    "Hallowed Sepulchre": "Hallowed Sepulchre",
    "Prifddinas rooftop": "Prifddinas Agility Course",
    "Brimhaven Agility Arena": "Brimhaven Agility Arena",
    "Werewolf Skullball": "Werewolf Skullball",
    # thieving
    "Blackjacking": "Maple blackjack",
    "Pyramid Plunder": "Pyramid Plunder",
    "Ardougne knights": "Knight of Ardougne",
    "Vyres": "Vyrewatch Sentinel",
    "Master farmers": "Master Farmer",
    "Sorceress's Garden": "Sorceress's Garden",
    # mining
    "Motherlode Mine": "Motherlode Mine",
    "Volcanic Mine": "Volcanic Mine",
    "3-tick iron / granite": "Iron ore",
    "Amethyst": "Amethyst",
    "Blast Mine": "Blast mine",
    # woodcutting
    "Forestry teaks": "Teak tree",
    "Sulliuscep": "Sulliuscep",
    "Redwoods": "Redwood tree",
    "Yews / Magics": "Yew tree",
    "Woodcutting Guild": "Woodcutting Guild",
    # runecraft
    "ZMI altar": "Ourania Altar",
    "Blood runes (Arceuus)": "Blood rune",
    "Lava runes (binding necklace)": "Lava rune",
    "Wrath runes": "Wrath rune",
    "Daeyalt essence": "Daeyalt essence",
    # farming
    "Tree / fruit tree runs": "Palm tree",
    "Herb runs": "Grimy ranarr weed",
    # smithing
    "Blast Furnace – gold bars": "Gold bar",
    "Blast Furnace – other bars": "Blast Furnace",
    "Giants' Foundry": "Giants' Foundry",
    "Cannonballs": "Dwarf multicannon",
    "Anvil smithing (plates/darts)": "Anvil",
    # crafting
    "Dragonhide bodies": "Black d'hide body",
    "Battlestaves": "Battlestaff",
    "Glassblowing / Superglass Make": "Superglass Make",
    "Gem cutting": "Dragonstone",
    # fletching
    "Darts": "Rune dart",
    "Broad bolts / bow stringing": "Broad bolts",
    # construction
    "Mahogany Homes": "Mahogany Homes",
    "Oak larders": "Oak plank",
    "Oak dungeon doors": "Oak door",
    "Mahogany tables": "Mahogany plank",
    "Teak garden benches": "Teak plank",
    # herblore
    "Unfinished potions": "Vial of water",
    "Prayer potions": "Prayer potion",
    "Super restores": "Super restore",
    "Stamina potions": "Stamina potion",
    "Super combat potions": "Super combat potion",
    "Extended super antifires": "Extended super antifire",
    # cooking
    "Jugs of wine": "Jug of wine",
    "1-tick karambwans": "Cooked karambwan",
    "Fish at Hosidius / Myths' Guild": "Myths' Guild",
    "Sharks / Anglerfish": "Shark",
    # firemaking
    "Wintertodt": "Wintertodt",
    "Burning logs at a bank": "Magic logs",
    "Forestry bonfires": "Forestry",
    "Fire pits / wilderness ring": "Bonfire",
    # sailing
    "Barracuda Trials": "The Tempor Tantrum",
    "Courier tasks": "Notice board",
    "Sea charting": "Sea charting",
    "Bounty tasks": "Cannon (facility)",
    "Shipwreck salvaging": "Shipwreck salvaging",
    "Deep sea trawling": "Deep sea trawling",
    "Crystal extractor": "Crystal extractor",
    "Ocean encounters": "Raft",
    # added in the method audit
    "Shooting Stars": "Shooting Stars",
    "Calcified rocks": "Calcified deposit",
    "Zalcano": "Zalcano",
    "Ironwood / rosewood trees": "Rosewood tree",
    "Blisterwood tree": "Blisterwood tree",
    "2-tick harpooning": "Raw swordfish",
    "Aerial fishing": "Aerial fishing",
    "Leechfin fishing": "Leechfin",
    "Razor-backed kebbits": "Razor-backed kebbit",
    "Falconry": "Falconry",
    "Colossal Wyrm course": "Colossal Wyrm Agility Course",
    "Wilderness Agility Course": "Wilderness Agility Course",
    "Stealing artefacts": "Stealing artefacts",
    "Varlamore valuables": "Civitas illa Fortis",
    "Rogues' Castle chests": "Rogues' Castle",
    "Lava runes with runners": "Lava rune",
    "Aether runes with runners": "Aether rune",
    "Mastering Mixology": "Mastering Mixology",
    "Mounted mythical capes": "Mythical cape (mounted)",
    "Shipwrights' workbench": "Shipwrights' Workbench",
    "Blessed bone shards": "Blessed bone shards",
    "Cremating urium remains": "Urium remains",
    "Gemstone Crab": "Gemstone Crab",
    "Scurrius": "Scurrius",
    "Crafting drift nets": "Drift net",
    "Bake Pie": "Bake Pie",
    "Rune items (3-bar)": "Rune platebody",
    "Bursting maniacal monkeys": "Ice Burst",
    "Tele-alch": "High Level Alchemy",
    "Monkfish": "Raw monkfish",
    "Dark crabs": "Raw dark crab",
    "Pest Control": "Pest Control",
    "Mud runes": "Mud rune",
    "Wyrmscraig": "Wyrmscraig",
    "Letvek and stymphikes": "Stymphike",
    "Bloodwood trees": "Bloodwood tree",
    "Rubium rocks": "Rubium rocks",
    "Infernal shale": "Infernal shale",
    # afk page
    "Bonecrusher and ash sanctifier": "Bonecrusher necklace",
    "Nightmare Zone, absorptions": "Nightmare Zone",
    "Bonfires": "Bonfire",
    "Range cooking": "Shark",
    "Cutting amethyst": "Amethyst",
    "Blood runes at Arceuus": "Blood rune",
    "Shipwreck salvaging with crew": "Shipwreck salvaging",
    # diaries
    "Hard diaries": "Achievement Diary",
    "Elite diaries": "Achievement Diary",
}

# Names that get an inline thumbnail on first mention in prose. Order matters
# only for overlapping strings; longer aliases are matched first automatically.
# alias -> wiki page title
PROSE_ENTITIES = {
    # slayer masters and bosses
    "Duradel": "Duradel",
    "Nieve": "Nieve",
    "Konar": "Konar quo Maten",
    "Krystilia": "Krystilia",
    "Turael": "Turael",
    "Vorkath": "Vorkath",
    "Zulrah": "Zulrah",
    "Muspah": "Phantom Muspah",
    "Wintertodt": "Wintertodt",
    "Tempoross": "Tempoross",
    "Herbiboar": "Herbiboar",
    "Sulliuscep": "Sulliuscep",
    "Sulphur Nagua": "Sulphur Nagua",
    "maniacal monkeys": "Maniacal monkey",
    "Menaphite thugs": "Menaphite Thug",
    "Ardougne knights": "Knight of Ardougne",
    # activities and locations
    "Guardians of the Rift": "Guardians of the Rift",
    "Hallowed Sepulchre": "Hallowed Sepulchre",
    "Motherlode Mine": "Motherlode Mine",
    "Nightmare Zone": "Nightmare Zone",
    "Mahogany Homes": "Mahogany Homes",
    "Giants' Foundry": "Giants' Foundry",
    "Blast Furnace": "Blast Furnace",
    "Pyramid Plunder": "Pyramid Plunder",
    "Volcanic Mine": "Volcanic Mine",
    "Chaos altar": "Chaos Temple (Wilderness)",
    "Ectofuntus": "Ectofuntus",
    "Rogues' Den": "Rogues' Den",
    "Sorceress's Garden": "Sorceress's Garden",
    "Shilo Village": "Shilo Village",
    "Fossil Island": "Fossil Island",
    "Varlamore": "Varlamore",
    "Prifddinas": "Prifddinas",
    "Hunters' Guild": "Hunter Guild",
    "Mining Guild": "Mining Guild",
    "Woodcutting Guild": "Woodcutting Guild",
    "Myths' Guild": "Myths' Guild",
    "Wilderness": "Wilderness",
    "Barracuda Trials": "The Tempor Tantrum",
    "Gwenith Glide": "The Gwenith Glide",
    "Lunar Isle": "Lunar Isle",
    "crystal extractor": "Crystal extractor",
    "captain's log": "Captain's log",
    "Pandemonium": "Pandemonium",
    # skilling outfits
    "Angler's outfit": "Angler's outfit",
    "Lumberjack outfit": "Lumberjack outfit",
    "Raiments of the Eye": "Raiments of the Eye",
    "Guild hunter outfit": "Guild hunter outfit",
    "Farmer's outfit": "Farmer's outfit",
    "Zealot's robes": "Zealot's robes",
    "Graceful outfit": "Graceful outfit",
    "Prospector kit": "Prospector kit",
    "Carpenter's outfit": "Carpenter's outfit",
    "Pyromancer outfit": "Pyromancer outfit",
    "Smiths' Uniform": "Smiths' Uniform",
    "Rogue equipment": "Rogue equipment",
    # capes and milestones
    "Max Cape": "Max cape",
    "Max cape": "Max cape",
    "Quest Cape": "Quest point cape",
    "Diary Cape": "Achievement diary cape",
    # gear and unlocks worth a picture
    "graceful": "Graceful outfit",
    "prospector kit": "Prospector kit",
    "pyromancer outfit": "Pyromancer outfit",
    "Smiths' outfit": "Smiths' Uniform",
    "Rogue's outfit": "Rogue equipment",
    "carpenter's outfit": "Carpenter's outfit",
    "Ardougne cloak": "Ardougne cloak 4",
    "Karamja gloves": "Karamja gloves 3",
    "Varrock armour": "Varrock armour 3",
    "Daeyalt essence": "Daeyalt essence",
    "birdhouse runs": "Oak bird house",
    "black chinchompas": "Black chinchompa",
    "red chins": "Red chinchompa",
    "chins": "Black chinchompa",
}


def all_titles():
    return sorted(set(METHOD_MEDIA.values()) | set(PROSE_ENTITIES.values()))
