"""Duradel task verdicts, lifted from the OSRS Wiki Slayer training guide.

Each row says what a task is worth, whether to do, skip or block it, and why.
Re-parse the wiki table if the guide changes.
"""

# tag: do | skip | block | lock (never unlock) | mixed (depends on your goal)
TASKS = [
    dict(name='Aberrant spectres', level='60', weight='7', tag='skip',
         rec='Skip unless hunting for herbs/seeds',
         xp='35,000',
         pros='Relatively low-effort task. Valuable herbs and seeds cover most of the costs of using the cannon.',
         cons='Cannot be lured into double-hit cannon spots properly, which results in mediocre experience rates.'),
    dict(name='Abyssal demons', level='85', weight='12', tag='mixed',
         rec='Do for XP; block for money',
         xp='80,000 (Magic) 53,000 (Venator Bow) 40,000 (Melee)',
         pros='Decent profit from abyssal whip drops. Decent experience when barraging. Decent experience and low-effort when using Venator bow.',
         cons='Long task and very commonly assigned.'),
    dict(name='Ankou', level='1', weight='5', tag='do',
         rec='Do',
         xp='55,000 (Magic)',
         pros='Decent experience and relatively fast task when barraging in the Catacombs of Kourend. While risky, barraging Ankou in the Wilderness Slayer Cave provides up to 90,000 Slayer experience per hour and drops will cover the cost of using Blighted ancient ice sacks .',
         cons='Barraging will result in a loss due to lack of valuable drops.'),
    dict(name='Araxytes', level='92', weight='10', tag='do',
         rec='Do',
         xp='100,000 (Cannon and Venator bow)',
         pros='Good experience, decent profit, and boss version available. Unextended tasks can be done for quick points.',
         cons='Venom resistance required.'),
    dict(name='Aviansie', level='1', weight='8', tag='lock',
         rec='Should not be unlocked',
         xp='10,000',
         pros="Kree'arra can be killed on task for good profit.",
         cons="Poor experience rates. Killing Kree'arra effectively requires very expensive equipment, and the profit is very inconsistent due to the value mostly being in the rare unique drops."),
    dict(name='Basilisks', level='40', weight='7', tag='mixed',
         rec="Don't unlock for XP; can unlock for profit or hunting the basilisk jaw on an ironman",
         xp='15,000',
         pros='Basilisk Knights can be killed on task for good profit.',
         cons='Poor experience rates.'),
    dict(name='Bloodveld', level='50', weight='8', tag='do',
         rec='Do',
         xp='100,000 (Cannon and Venator Bow) 80,000 (Cannon and Melee)',
         pros="Good experience rates when cannoning mutated bloodvelds in the Meiyerditch Laboratories or Buccaneers' Laboratory . Drops cover the cost of using the cannon if in Meiyerditch Laboratories.",
         cons='Travelling to the Meiyerditch Laboratories can take a while. Using a cannon will result in a loss in the Stronghold Slayer Cave .'),
    dict(name='Black demons', level='1', weight='8', tag='block',
         rec='Block/skip unless killing demonic gorillas for profit/uniques',
         xp='45,000',
         pros='Decent experience rates, low-effort task. Demonic gorillas can be killed for good profit at the expense of experience rates.',
         cons='Long task, especially if killing demonic gorillas. Using the cannon will result in a loss.'),
    dict(name='Black dragons', level='1', weight='9', tag='do',
         rec='Do',
         xp='30,000',
         pros='If killing baby black dragons , a very fast task when unextended. Brutal black dragons can be killed for profit at higher levels.',
         cons='Mediocre experience rates.'),
    dict(name='Blue dragons', level='1', weight='4', tag='skip',
         rec='Skip if not killing Vorkath for profit. (Compare vs. Salve amulet beforehand)',
         xp='25,000',
         pros='Vorkath can be killed on task for good and consistent profit.',
         cons='Poor experience rates.'),
    dict(name='Bosses', level='Varies (1 for all except a few)', weight='12', tag='mixed',
         rec='Only unlock if you want the slayer helm bonus vs. bosses; XP can be very poor.',
         xp='Generally poor, but varies',
         pros='Can be a relatively quick task depending on what boss you get, in addition to 5,000 Slayer experience upon completion of the task. Can potentially receive very valuable rare drops.',
         cons='Some bosses can be rather annoying to kill, and requires 200 Slayer points to unlock boss tasks.'),
    dict(name='Cave horrors', level='58', weight='4', tag='skip',
         rec='Skip unless you are an ironman hunting for a black mask',
         xp='25,000',
         pros='Relatively fast task. Drops cover the cost of using the cannon.',
         cons='Poor experience rates. Not worth doing for XP unless Slayer points are an issue.'),
    dict(name='Cave kraken', level='87', weight='9', tag='block',
         rec='Block after achieving the kraken Combat Achievements',
         xp='15,000',
         pros='Decent and low-effort profit when killing the boss variant .',
         cons='Poor experience rates. Killing cave krakens will result in a guaranteed loss due to the supplies needed to kill them with little net gain.'),
    dict(name='Dagannoth', level='1', weight='9', tag='do',
         rec='Do',
         xp='85,000',
         pros='Good experience rates.',
         cons='Can be crowded in the Lighthouse Dungeon . Using the cannon will result in a loss.'),
    dict(name='Dark beasts', level='90', weight='11', tag='do',
         rec='Do',
         xp='42,000',
         pros='Fast task when unextended. Relatively low-effort task.',
         cons='Somewhat mediocre experience rates.'),
    dict(name='Drakes', level='84', weight='8', tag='skip',
         rec="Skip/Block unless you're an ironman hunting their uniques",
         xp='35,000',
         pros='Relatively low-effort task with high combat stats.',
         cons='Mediocre experience rates and long task. Not worth doing unless Slayer points are an issue.'),
    dict(name='Dust devils', level='65', weight='5', tag='do',
         rec='Do',
         xp='100,000–110,000 (Magic) 60,000 (Venator bow) 35,000 (Melee)',
         pros='Good experience rates when barraging in the Catacombs of Kourend. Drops cover the rune costs.',
         cons='Can be crowded in the Catacombs of Kourend.'),
    dict(name='Elves', level='1', weight='4', tag='skip',
         rec='Skip',
         xp='25,000',
         pros='Relatively low-effort task.',
         cons='Poor experience rates. Not worth doing unless Slayer points are an issue.'),
    dict(name='Fire giants', level='1', weight='7', tag='mixed',
         rec='Do for magic XP, otherwise skip',
         xp='40,000',
         pros='Relatively low-effort task. Relatively fast with imbued black mask and water wave+.',
         cons='Somewhat mediocre experience rates. Using the cannon will result in a loss. Good Magic XP using water spells due to 100% weakness.'),
    dict(name='Fossil Island Wyverns', level='66, 82', weight='5', tag='block',
         rec='Block with the unique unlock',
         xp='15,000',
         pros='Relatively low-effort task.',
         cons='Poor experience rates and mediocre profit. Not worth doing unless Slayer points are an issue.'),
    dict(name='Frost dragons', level='1', weight='5', tag='mixed',
         rec='Do for profit; skip for XP',
         xp='30,000',
         pros='Relatively low-effort task. Decent profit.',
         cons='Mediocre experience rates. Requires travelling with a boat that can withstand icy seas when visiting for the first time.'),
    dict(name='Gargoyles', level='75', weight='8', tag='mixed',
         rec='Do for profit; skip for XP',
         xp='30,000',
         pros='Decent profit, relatively low-effort task. Grotesque Guardians can be killed on task.',
         cons='Mediocre experience rates. Can be crowded in the Slayer Tower.'),
    dict(name='Greater demons', level='1', weight='9', tag='skip',
         rec='Skip unless killing Tormented Demons or Kril for profit',
         xp='38,000 (Regular) 50,000 (Tormented Demons)',
         pros="Relatively fast task when unextended. Relatively low-effort task. Tormented Demons and K'ril Tsutsaroth can be killed on task for profit.",
         cons='Mediocre experience rates and commonly assigned. Using the cannon will result in a loss.'),
    dict(name='Gryphons', level='51', weight='7', tag='mixed',
         rec='Can be unlocked for XP. Should not be unlocked for profit.',
         xp='50,000',
         pros='Good experience rates when cannoning in multicombat areas.',
         cons='Using the cannon will result in a loss.'),
    dict(name='Hellhounds', level='1', weight='10', tag='block',
         rec='Block unless killing Cerberus for profit',
         xp='40,000 (Regular) 25,000 (Cerberus)',
         pros='Cerberus can be killed on task for good long-term profit. Relatively low-effort task if killing regular hellhounds, and good source of hard clue scrolls .',
         cons='Commonly assigned and long task. Using the cannon will result in a loss due to lack of drops. Killing Cerberus effectively requires expensive equipment, and the profit is very inconsistent due to the value mostly being in the rare unique drops.'),
    dict(name='Kalphites', level='1', weight='9', tag='do',
         rec='Do',
         xp='75,000',
         pros='Good experience rates when cannoning the soldiers. Relatively low-effort task.',
         cons='Using the cannon will result in a loss.'),
    dict(name='Kurask', level='70', weight='4', tag='mixed',
         rec='Do for profit; skip for XP',
         xp='20,000',
         pros='Somewhat decent profit.',
         cons='Can only be harmed with leaf-bladed weaponry, broad bolts or Magic Dart, which results in poor experience rates. Not worth doing for XP unless Slayer points are an issue.'),
    dict(name='Lizardmen', level='1', weight='10', tag='lock',
         rec='Should not be unlocked',
         xp='50,000',
         pros='Decent experience rates when cannoning lizardmen. Relatively fast task.',
         cons='Commonly assigned, which makes this task not worth unlocking. Using the cannon will result in a loss.'),
    dict(name='Metal dragons', level='1', weight='14', tag='mixed',
         rec='Do for profit; block for XP',
         xp='30,000 (Iron, Steel and Mithril) 15,000 (Adamant and Rune)',
         pros='Fast task with high combat stats and when using a dragon hunter lance.',
         cons='Mediocre to poor experience rates. Higher level dragons can be difficult to kill without good equipment.'),
    dict(name='Mutated Zygomites', level='57', weight='2', tag='skip',
         rec='Skip',
         xp='10,000',
         pros='Relatively fast task.',
         cons='Poor experience rates. Not worth doing unless Slayer points are an issue.'),
    dict(name='Nechryael', level='80', weight='9', tag='do',
         rec='Do',
         xp='100,000 (Magic) 40,000 (Melee)',
         pros='Good experience rates when barraging in the Catacombs of Kourend . Decent profit if meleeing.',
         cons='Often crowded in the Catacombs of Kourend.'),
    dict(name='Red dragons', level='1', weight='8', tag='lock',
         rec='Should not be unlocked',
         xp='30,000',
         pros='Decent profit with high stats and when using a dragon hunter lance.',
         cons='Mediocre experience rates.'),
    dict(name='Skeletal Wyverns', level='72', weight='7', tag='skip',
         rec='Skip',
         xp='15,000',
         pros='Decent profit with high combat stats and when using a dragon hunter lance.',
         cons='Poor experience rates.'),
    dict(name='Smoke devils', level='93', weight='9', tag='do',
         rec='Do',
         xp='150,000 (Magic) 55,000 (Melee)',
         pros='Barraging smoke devils currently offers the best experience rates in the game. Drops cover the rune costs.',
         cons='Luring smoke devils properly requires a lot of practice and effort.'),
    dict(name='Spiritual creatures', level='63, 68, 83', weight='7', tag='skip',
         rec='Skip',
         xp='25,000',
         pros='Mages can give decent profit and have relatively low hitpoints (75 for Zamorak, 85 for Saradomin)',
         cons='Need to bring energy or stamina potions and restore potions if going to GWD via Trollheim due to chill . Poor experience rates everywhere. Not worth doing for XP unless Slayer points are an issue.'),
    dict(name='Suqah', level='1', weight='8', tag='mixed',
         rec='Do for XP; skip for profit',
         xp='55,000',
         pros='Decent experience rates. Relatively fast task when unextended.',
         cons='No notable drops to cover the cost of using the cannon. Requires good defensive armour as well as Protect from Magic since they hit hard with both attack styles.'),
    dict(name='Trolls', level='1', weight='6', tag='mixed',
         rec='Do for XP; skip for profit',
         xp='50,000',
         pros='Decent experience rates when cannoning ice trolls on Jatizso or mountain trolls at Mount Quidamortem. Drops cover some of the costs of using the cannon.',
         cons='Ice trolls deal heavy damage. Travelling to Jatizso can take a while.'),
    dict(name='TzHaar', level='1', weight='10', tag='do',
         rec='Do if you have access to Blood Barrage /can consistently do Fight Caves . Otherwise, do not unlock.',
         xp='100,000 (Magic) Varies (Inferno/Fight Caves)',
         pros="Good experience rates when barraging in the inner part of Mor Ul Rek. Drops cover the rune costs. Alternatively, the option to do the Fight Caves on task will be given, or The Inferno if it's already completed. This task can be 'skipped' easily by entering and immediately leaving the Fight Caves, or by dying inside the Fight Caves or The Inferno.",
         cons='Barraging requires using blood spells. Completing the Inferno or the Fight Caves quickly requires having expensive equipment.'),
    dict(name='Vyrewatch', level='38', weight='8', tag='mixed',
         rec='Should not be unlocked for XP. Can be unlocked for profit.',
         xp='15,000',
         pros='Killing Vyrewatch Sentinels in Darkmeyer can yield a somewhat decent profit. Does not require supplies, as prayer can be restored at the Statue .',
         cons='Can only be harmed with the Ivandis flail or blisterwood flail , which results in poor experience rates.'),
    dict(name='Warped creatures', level='56', weight='8', tag='lock',
         rec='Should not be unlocked',
         xp='55,000 (Cannon)',
         pros='Decent experience when using a cannon. Drops cover cost of cannonballs. Food drops and bones to peaches can sustain a high level player.',
         cons='Mediocre experience when not using a cannon. Dungeon is multi-combat and creatures attack with both melee and range.'),
    dict(name='Waterfiends', level='1', weight='2', tag='skip',
         rec='Skip',
         xp='15,000',
         pros='Somewhat decent drops.',
         cons='Poor experience rates. Requires some attention due to using two different styles at fairly high accuracy. Not worth doing unless Slayer points are an issue.'),
    dict(name='Wyrms', level='62', weight='8', tag='skip',
         rec="Skip unless you're an ironman hunting their uniques",
         xp='35,000',
         pros='Somewhat decent drops. Magma strykewyrms offer better XP and have better drops.',
         cons='Mediocre experience rates. Not worth doing unless Slayer points are an issue.'),
]
